apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: Repository
metadata:
  name: chartmuseum-auth
  namespace: kubebb-system
spec:
  url: http://chartmuseum-auth.kubebb-addons.svc.cluster.local:8080
  authSecret: mysecret
  pullStategy:
    intervalSeconds: 120
    retry: 5
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: kubebb-system
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
