{{- if .Values.tls.enable }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: {{ .Release.Name}}.{{ .Release.Namespace}}.svc.cluster.local
  dnsNames:
  - {{ .Values.service.servicename | default (include "chartmuseum.fullname" .) }}.{{ .Release.Namespace }}.svc.cluster.local
  - {{ .Values.service.servicename | default (include "chartmuseum.fullname" .) }}.{{ .Release.Namespace }}.svc
{{- range $value := .Values.tls.dnsnames }}
  - {{ $value}}
{{- end }}
  isCA: true
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}
  secretName: {{ .Release.Name }}-cert
{{- end }}
