# Default values for initializr-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: 192.168.90.214/system_containers
  repository: apm-operator-server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v5.6.0"
certImage:
  registry: 192.168.90.214
  repository: system_containers/operator-cert-apm
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v5.6.0"

imagePullSecrets: []
nameOverride: "apm-operator"
fullnameOverride: "apm-operator"
namespaceOverride: "apm-system"
appName: "springcloud"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 512Mi

nodeSelector: {}

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

affinity: {}

psp:
  create: true
