apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: ComponentPlan
metadata:
  name: fabric-bc-apis
  namespace: kubebb-system
spec:
  approved: true
  name: fabric-bc-apis
  version: v0.0.1
  override:
    set:
      - ingressDomain={ingressNodeIP}.nip.io
      - iamServer=https://oidc-server.u4a-system
      - env.k8sOIDCProxyURL=https://k8s.{ingressNodeIP}.nip.io
      - env.OIDCServerURL=https://portal.{ingressNodeIP}.nip.io/oidc
      - env.OIDCServerClientID=bff-client
      - env.OIDCServerClientSecret=61324af0-1234-4f61-b110-ef57013267d6
      - env.imageNamespace=hyperledgerk8s
      - env.imageFabricCATag=iam-20230131
      - env.imageFabricOrdererTag=2.4.7
      - env.imageFabricPeerTag=2.4.7-external
      - env.minioAccessKey=ylc9dZGbZg2oYgnE
      - env.minioSecretKey=ykCAHG3snLaToaRsbPo3rhCyZNqCKcIt
      - env.minioEndpoint=fabric-minio.baas-system.svc.cluster.local
      - image=hyperledgerk8s/bc-apis:20230703.143401.87
      - hostAliases[0].hostnames={oidc.{ingressNodeIP}.nip.io}
      - hostAliases[0].ip={ingressNodeIP}
  component:
    name: kubebb.bc-apis
    namespace: kubebb-system
