apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: ComponentPlan
metadata:
  name: my-minio
  namespace: kubebb-addons
spec:
  approved: true
  name: my-minio # similar to helm release name
  version: 5.0.8
  component:
    name: kubebb.minio
    namespace: kubebb-system
  override:
    set:
      - rootUser=admin
      - rootPassword=Passw0rd!
