apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rating-rolebinding
  namespace: kubebb-system
subjects:
  - kind: ServiceAccount
    name: rating-service-account
    namespace: kubebb-system
roleRef:
  kind: ClusterRole
  name: rating-clusterrole
  apiGroup: rbac.authorization.k8s.io
